version: '3'

services:
 gist2pill:

  build: .

  env_file:
    - .env

  environment:
    APP_NAME: "${APP_NAME}"
    GH_REPO_OWNER: "${GH_REPO_OWNER}"
    GH_REPO: "${GH_REPO}"
    GH_TOKEN: "${GH_TOKEN}"


  volumes:
   - .:/code